#!/usr/bin/python
import time
from modGrid import *
from modPlayer import *
from modBeast import *
from modRock import *
from modHBeast import *
from modSBeast import *
from modEggs import *

def main():
    g = Grid()
    b = Beast()
    p = Player()
    g.addElement(p,1,1)
    g.addElement(b,10,10)
    g.fillGridRandomWalls()
    g.fillGridRocks()
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()
    g.movePlayer(p,g.MOVE_E)
    time.sleep(0.5)
    g.moveBeast(b,p)
    g.renderGridAscii()

#this calls the 'main' function when this script is executed
if __name__ == '__main__': main()

